/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_rhinocorps_simajin_gin_DrawWindow */

#ifndef _Included_com_rhinocorps_simajin_gin_DrawWindow
#define _Included_com_rhinocorps_simajin_gin_DrawWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhinocorps_simajin_gin_DrawWindow
 * Method:    drawSomething
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhinocorps_simajin_gin_DrawWindow_drawSomething
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
